name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Tool
      run: dotnet tool install --global dotnet-ef
    - name: Build
      run: dotnet build --no-restore
    - name: Migrate
      working-directory: BikeHistory
      run: dotnet ef migrations add init
    - name: Update DB
      working-directory: BikeHistory
      run: dotnet ef database update
    - name: Test
      run: dotnet test --verbosity normal